### ISSUE TITLE
Tracking deployments has limited functionality

### ISSUE THREAD

**Issue by vedrani** [atlassian/github-for-jira#2421]
Tracking of GH deployments and transforming them to Jira deployments is limited and it's leaking Jira into Github VSC:
* Parse only Jira key from commit message 
  * Leaks Jira app rules into commit message guidelines and forcing change of commit message guidelines
* Doesn't analyse GH Deployment `payload` field or other GH deployment fields 

All that results in stiff and strict solution for tracking deployments.

Instead Jira App for GH should parse Jira keys from:
* PR connected to commit
  * PR title
  * PR body
* GH deployment `payload` field 
  * This would allow engineers to inject Jira keys manually in CI adding flexibility and robustness to it considering we are running GHA in various cases  

Simplest solution would be just to add [here](https://github.com/atlassian/github-for-jira/blob/main/src/transforms/transform-deployment.ts#L371) also `deployment.payload`

```
jiraIssueKeyParser(`${deployment.ref}\n${message}\n${allCommitsMessages}\n${deployment.payload}`),
```

And we would have capability to inject Jira keys from outside in flexible way without requirement to change commit messages to contain Jira key.

**Comment by Brijeshoo7** [comment]
Hello @vedrani ,

I Have multi branch deployment strategy in GitHub, like if someone merge in frontend branch then it triggers deployment in infrastructure branch for dev environment also I have manual deployment script, so If i create PR under infrastructure branch and merge it I am able to get deployments information in Jira where as if someone merges into frontend branch then it only shows branch status like merged and build information only.

infrastructure branch code:
```
name: Develop CD
on:
  push:
    branches: [ dev ]
jobs:
  build:
    name: for-cd
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Call
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{secrets.CD_GITHUB_TOKEN}}" \
            https://github.com/repos/org/infra/actions/workflows/dispatch-cd.yml/dispatches \
            -d '{"ref":"dev","inputs":{"component":"frontend"}}' || exit 1
           
```

Just code test yaml:
```
name: Develop / Feature branch CI
on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened]
  push:
    branches: ['feat/**']
jobs:
  sonarcloud:
    name: branch-quality-check
    runs-on: ubuntu-latest
    steps:
      - name: Setup Github Actions checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Github Actions setup-Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install tox and other dependencies
        run: pip install tox
      - name: Run tox
        run: tox
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SO_TOKEN }}
```
Below is the front end branch ticket info from jira:
![image](https://github.com/atlassian/github-for-jira/assets/88958817/bb7f7d41-561e-4c4e-b58d-0e99cbbd1f60)

below is infra branch ticket info:
![image](https://github.com/atlassian/github-for-jira/assets/88958817/96a16e1f-ffa0-4dd6-b7f3-9b991fa0e3f6)


can you help or suggest anything?

**Comment by aareman** [comment]
After some experimentation I was able to get it to work by using `pull_request_target`. Here is my working example. I only had the ticket id in the branch name, not in the commit messages or pr title/body.
```yaml
name: Deploy to prod

on:
  pull_request_target:
    types: [closed]
    branches:
      - master
  

jobs:
  cd:
    name: Deploy to Production
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        env:
          MERGED_BRANCH: ${{ github.event.pull_request.head.ref || '' }}
        run: |
          echo "MERGED_BRANCH=$MERGED_BRANCH" >> $GITHUB_ENV

      - name: Print merged branch name
        run: |
          echo "Merged branch: ${{ env.MERGED_BRANCH }}"

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          ref: ${{ github.event.pull_request.head.ref || '' }}
          environment-url: https://testurl
          environment: production

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: "${{ github.token }}"
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: "success"

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: "${{ github.token }}"
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: "failure"

```
